Updated Footer
HackAtUCI/irvinehacks-site pull request #409
Opened 2024-12-02 08:15 UTC by cyriljoby

Resolves #391 

Created footer with icons and links to Hack's instagram, tiktok, mail and discord.
Updated the heart icon to reflect this year's design.

2024-12-03 03:17 UTC, waalbert requested changes
Awesome work Cyril! Here are a few requested changes

2024-12-03 03:17 UTC, waalbert commented on apps/site/src/lib/components/Footer/Footer.module.scss
> +	// background-color: #432810;
Chore: remove unused comment

2024-12-03 03:17 UTC, waalbert commented on apps/site/src/lib/components/Footer/Footer.tsx
>  				<p className="m-0">in Irvine, CA <span className="max-[600px]:hidden">•</span></p>
Due to Student Center regulations, we have to specify that IrvineHacks is hosted by us, Hack at UCI, so switch the text of the footer to say "Made with ❤️ by Hack at UCI ..."

And that means we also have to add our Hack logo linked to our club site.

2024-12-03 06:53 UTC, taesungh commented on apps/site/src/assets/logos/discord.svg
This does not appear to be the official Discord logo. Please make sure to use the official version (e.g. `discord-mark-white.svg`) from [Discord's Branding Guidelines](https://discord.com/branding).

2024-12-03 06:53 UTC, taesungh commented on apps/site/src/assets/logos/tiktok.svg
Same note here: this does not appear to be an official TikTok logo, please use `TikTok-Social-Icon-Rounded-Square-Mono-Black.svg` from the [TikTok Brand Guidelines](https://tiktokbrandbook.com).

2024-12-03 19:15 UTC, waalbert requested changes
Some more things

2024-12-03 19:15 UTC, waalbert commented on apps/site/src/lib/components/Footer/Footer.tsx
> +	// ;#2878A6
Chore: remove unused comment

2024-12-03 21:31 UTC, taesungh commented on apps/site/src/lib/components/Footer/Footer.tsx
> +		link: "mailto:hack@uci.edu",
@waalbert, could you set up forwarding on a vanity email instead, e.g. contact@irvinehacks.com ?

2024-12-04 00:40 UTC, waalbert commented on apps/site/src/lib/components/Footer/Footer.tsx
> +		link: "mailto:hack@uci.edu",
Yes, we will use the vanity email instead.

2024-12-04 20:31 UTC, waalbert submitted a review, later dismissed
Thanks for the work Cyril! Don't merge until the new Landing Page is completed

2024-12-06 13:18 UTC, waalbert approved these changes

2024-12-06 13:18 UTC, merged