Portal UI
HackAtUCI/irvinehacks-site pull request #412
Opened 2024-12-03 02:28 UTC by jotalis

Summary
- Updated the UI for the portal page according to the Figma

Test Plan
- Go to ApplicantPortal.tsx and comment out lines 24-28
- Add "let status = identity.status; status = PortalStatus.pending;" 
- Test each of the possible PortalStatus states by changing what status is set to; e.g. status = PortalStatus.waived;...
- Ensure that the UI looks right

2024-12-05 01:08 UTC, waalbert requested changes
Awesome work Jay! Here are a few suggestions:

2024-12-05 01:08 UTC, waalbert commented on apps/site/src/app/(main)/portal/@applicant/components/timeline/RSVP.tsx
Suggestion [repeating]: rename this file to `RSVPComponent` to follow the consistency of `TimelineComponent`

2024-12-05 01:08 UTC, waalbert commented on apps/site/src/app/(main)/portal/@applicant/components/timeline/Submission.tsx
Suggestion [repeating]: rename this file to `SubmissionComponent` to follow the consistency of `TimelineComponent`

2024-12-05 01:08 UTC, waalbert commented on apps/site/src/app/(main)/portal/@applicant/components/timeline/Verdict.tsx
Suggestion [repeating]: rename this file to `VerdictComponent` to follow the consistency of `TimelineComponent`

2024-12-05 01:08 UTC, waalbert commented on apps/site/src/app/(main)/portal/@applicant/components/timeline/Waiver.tsx
Suggestion [repeating]: rename this file to `WaiverComponent` to follow the consistency of `TimelineComponent`

2024-12-05 01:50 UTC, IanWearsHat requested changes
Great job working on this complex task especially with all of its different statuses. I left a few comments below.

2024-12-05 01:50 UTC, IanWearsHat commented on apps/site/src/app/(main)/portal/@applicant/components/timeline/TimelineComponent.tsx
> +		</div>
Issue: There should be some particle assets to the sides of the Timeline.

![image](https://github.com/user-attachments/assets/908dbca4-a5f4-4d49-86bb-e4d7d115a637)

2024-12-05 01:50 UTC, IanWearsHat commented on apps/site/src/app/(main)/portal/@applicant/components/timeline/TimelineComponent.tsx
> +	const baseStyles = `flex items-center justify-between mb-4 md:mb-8 border-[2px] md:border-[5px] border-[var(--color-white)]`;
Nitpick: string should be in double quotes if there is nothing templated

2024-12-05 01:50 UTC, IanWearsHat commented on apps/site/src/app/(main)/portal/@applicant/components/timeline/VerticalTimeline.tsx
> +		<div className="">
Suggestion: empty `className` prop could be removed

2024-12-05 19:38 UTC, IanWearsHat approved these changes
Looks good to me! Thanks again Jay for working on this complicated task. Squash and merge when ready.

2024-12-06 00:22 UTC, waalbert requested changes
One more thing

2024-12-06 00:22 UTC, waalbert commented on apps/site/src/app/(main)/portal/@applicant/components/ReturnHome.tsx
> +export default function SignWaiver() {
Issue: `SignWaiver` is already a component defined elsewhere, so naming this `ReturnHome` will reduce confusion

2024-12-06 00:31 UTC, waalbert approved these changes

2024-12-06 00:32 UTC, merged