Adding Landing Page
HackAtUCI/irvinehacks-site pull request #413
Opened 2024-12-03 06:44 UTC by Bl20052005

2024-12-04 22:04 UTC, waalbert requested changes
Looks awesome Bo! Here are a few fixes

2024-12-04 22:04 UTC, waalbert commented on apps/site/src/app/(main)/(home)/sections/Landing/LandingUnlocked.tsx
Issue: on larger screen widths `> 1920px`, you can start to see the edges outside of the assets, so to fix this can you split up the assets into halves and load them in that way?

2024-12-05 03:42 UTC, Bl20052005 commented on apps/site/src/app/(main)/(home)/sections/Landing/LandingUnlocked.tsx
This is possible for the pillars and background castle, but there are a couple of assets like clouds and background pillars that cannot be split up as it would make for a very jarring cut-off

2024-12-05 04:33 UTC, Bl20052005 commented on apps/site/src/app/(main)/(home)/sections/Landing/LandingUnlocked.tsx
As it turns out this is not needed at all

2024-12-06 12:46 UTC, waalbert approved these changes
Thanks for the work Bo and Ian!

2024-12-06 13:05 UTC, waalbert approved these changes

2024-12-06 13:05 UTC, merged